name: ci

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 0.29.0
        - 1.0.0
        - 1.1.0
        - 1.2.0
        - 1.2.1
        - 2.0.0

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        docker build \
            -t ngalayko/bazel-action:${{ matrix.version }} \
            --build-arg bazel_version=${{ matrix.version }} \
            .
